export const transactions = [
  {
    account_id: '6qPok7PWD6sMm7WXdEw5cbXzqLQjNLubveWPn',
    account_owner: null,
    amount: 5.4,
    authorized_date: '2022-11-30',
    authorized_datetime: null,
    category: ['Travel', 'Taxi'],
    category_id: '22016000',
    check_number: null,
    date: '2022-12-01',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    merchant_name: 'Uber',
    name: 'Uber 063015 SF**POOL**',
    payment_channel: 'in store',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_id: 'Bj8rom8xXZs9oXVAmnvaCB6XewgA8QuLQ4M99',
    transaction_type: 'special',
    unofficial_currency_code: null
  },
  {
    account_id: '6qPok7PWD6sMm7WXdEw5cbXzqLQjNLubveWPn',
    account_owner: null,
    amount: -500,
    authorized_date: '2022-11-29',
    authorized_datetime: null,
    category: ['Travel', 'Airlines and Aviation Services'],
    category_id: '22001000',
    check_number: null,
    date: '2022-11-29',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    merchant_name: 'United Airlines',
    name: 'United Airlines',
    payment_channel: 'in store',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_id: '3RaQZNag5bU5gp7GKAzxt3GlvdkA1Rt8BZl7d',
    transaction_type: 'special',
    unofficial_currency_code: null
  },
  {
    account_id: '6qPok7PWD6sMm7WXdEw5cbXzqLQjNLubveWPn',
    account_owner: null,
    amount: 12,
    authorized_date: '2022-11-28',
    authorized_datetime: null,
    category: ['Food and Drink', 'Restaurants', 'Fast Food'],
    category_id: '13005032',
    check_number: null,
    date: '2022-11-28',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: '3322'
    },
    merchant_name: "McDonald's",
    name: "McDonald's",
    payment_channel: 'in store',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_id: 'xjoE6JoVMqsbrkdxa8neuMk7RQZK4vfAq645r',
    transaction_type: 'place',
    unofficial_currency_code: null
  },
  {
    account_id: '6qPok7PWD6sMm7WXdEw5cbXzqLQjNLubveWPn',
    account_owner: null,
    amount: 4.33,
    authorized_date: '2022-11-28',
    authorized_datetime: null,
    category: ['Food and Drink', 'Restaurants', 'Coffee Shop'],
    category_id: '13005043',
    check_number: null,
    date: '2022-11-28',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    merchant_name: 'Starbucks',
    name: 'Starbucks',
    payment_channel: 'in store',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_id: 'dLKGRrKVbXU4ALgEXZNru94lbaBrQ7C6mJE8g',
    transaction_type: 'place',
    unofficial_currency_code: null
  },
  {
    account_id: '6qPok7PWD6sMm7WXdEw5cbXzqLQjNLubveWPn',
    account_owner: null,
    amount: 89.4,
    authorized_date: '2022-11-26',
    authorized_datetime: null,
    category: ['Food and Drink', 'Restaurants'],
    category_id: '13005000',
    check_number: null,
    date: '2022-11-27',
    datetime: null,
    iso_currency_code: 'USD',
    location: {
      address: null,
      city: null,
      country: null,
      lat: null,
      lon: null,
      postal_code: null,
      region: null,
      store_number: null
    },
    merchant_name: null,
    name: 'SparkFun',
    payment_channel: 'in store',
    payment_meta: {
      by_order_of: null,
      payee: null,
      payer: null,
      payment_method: null,
      payment_processor: null,
      ppd_id: null,
      reason: null,
      reference_number: null
    },
    pending: false,
    pending_transaction_id: null,
    personal_finance_category: null,
    transaction_code: null,
    transaction_id: 'aZAoRlAVDXHxXbwlr6PLtoxA6bklMgIezZ5Ag',
    transaction_type: 'place',
    unofficial_currency_code: null
  }
];
